### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/androidx/viewmodel/GetViewModelKt;

### ISSUE THREAD

**Issue by jakepurple13** [Koitharu/WorkInspector#2]
I'm getting a new issue now:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/androidx/viewmodel/GetViewModelKt;
                                                                                                    	at org.koitharu.workinspector.ui.workers.WorkersListFragment$special$$inlined$viewModel$default$2.invoke(FragmentVM.kt:83)
                                                                                                    	at org.koitharu.workinspector.ui.workers.WorkersListFragment$special$$inlined$viewModel$default$2.invoke(FragmentVM.kt:49)
                                                                                                    	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:98)
                                                                                                    	at org.koitharu.workinspector.ui.workers.WorkersListFragment.getViewModel(WorkersListFragment.kt:21)
                                                                                                    	at org.koitharu.workinspector.ui.workers.WorkersListFragment.onViewCreated(WorkersListFragment.kt:35)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3269)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3187)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8084)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3700)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7881)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.androidx.viewmodel.GetViewModelKt" on path: DexPathList[[zip file "/data/app/~~F5jdGTjJiIheihMl601g9Q==/com.gabb.location_client_v2-CzMe_DQpdIaMEc7OiFj7EA==/base.apk"],nativeLibraryDirectories=[/data/app/~~F5jdGTjJiIheihMl601g9Q==/com.gabb.location_client_v2-CzMe_DQpdIaMEc7OiFj7EA==/lib/arm64, /data/app/~~F5jdGTjJiIheihMl601g9Q==/com.gabb.location_client_v2-CzMe_DQpdIaMEc7OiFj7EA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at org.koitharu.workinspector.ui.workers.WorkersListFragment$special$$inlined$viewModel$default$2.invoke(FragmentVM.kt:83) 
                                                                                                    	at org.koitharu.workinspector.ui.workers.WorkersListFragment$special$$inlined$viewModel$default$2.invoke(FragmentVM.kt:49) 
                                                                                                    	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:98) 
                                                                                                    	at org.koitharu.workinspector.ui.workers.WorkersListFragment.getViewModel(WorkersListFragment.kt:21) 
                                                                                                    	at org.koitharu.workinspector.ui.workers.WorkersListFragment.onViewCreated(WorkersListFragment.kt:35) 
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286) 
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114) 
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675) 
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3269) 
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3187) 
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263) 
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350) 
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251) 
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455) 
                                                                                                    	at android.app.Activity.performStart(Activity.java:8084) 
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3700) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7881) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
```

I don't know if it's something I'm missing. My project has the dependencies for the koin view models.

**Comment by jakepurple13** [comment]
It all works now!
